"""Dump a real compare response as a TypeScript module for the frontend's
offline fallback (so the Solver page renders a meaningful example even when the
API is not running)."""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fastapi.testclient import TestClient

from app.main import app

c = TestClient(app)
payload = {
    "state": {
        "stage": "midgame", "hp": 58, "gold": 42, "level": 6,
        "board_strength": "weak", "bench_value": "medium", "pairs": 2,
        "items": "medium", "lobby_tempo": "high", "goal": "top4",
    },
    "n_rollouts": 4000,
}
data = c.post("/api/compare", json=payload).json()
data["cached"] = False

out_path = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "frontend", "lib", "sampleResult.ts",
)
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by backend/scripts/make_sample.py — a real solver\n")
    f.write("// response used as an offline fallback when the API is unreachable.\n")
    f.write("import type { CompareResponse } from './types';\n\n")
    f.write("export const SAMPLE_RESULT: CompareResponse = ")
    f.write(json.dumps(data, indent=2))
    f.write(" as const;\n")
print("wrote", out_path)
