// Auto-generated by backend/scripts/make_sample.py — a real solver
// response used as an offline fallback when the API is unreachable.
import type { CompareResponse } from './types';

export const SAMPLE_RESULT: CompareResponse = {
  "state": {
    "stage": "midgame",
    "hp": 58,
    "gold": 42,
    "level": 6,
    "board_strength": "weak",
    "bench_value": "medium",
    "pairs": 2,
    "items": "medium",
    "lobby_tempo": "high",
    "goal": "top4"
  },
  "results": [
    {
      "key": "roll_30",
      "label": "Roll to 30",
      "expected_placement": 5.29,
      "top4_rate": 0.3118,
      "first_rate": 0.0043,
      "bot4_rate": 0.6883,
      "risk": 1.573,
      "distribution": [
        0.0043,
        0.0385,
        0.1,
        0.169,
        0.2172,
        0.2278,
        0.169,
        0.0742
      ],
      "ev_score": 0.5015,
      "branches": [
        {
          "label": "Win the next fight",
          "prob": 0.477,
          "expected_placement": 4.864255765199162
        },
        {
          "label": "Lose the next fight",
          "prob": 0.523,
          "expected_placement": 5.672562141491396
        }
      ],
      "explanation": "Spends gold to find upgrades now; stabilizes the board at some economic cost (best line: 31% top-4, avg 5.3)."
    },
    {
      "key": "save",
      "label": "Save",
      "expected_placement": 5.43,
      "top4_rate": 0.2833,
      "first_rate": 0.0053,
      "bot4_rate": 0.7167,
      "risk": 1.595,
      "distribution": [
        0.0053,
        0.0335,
        0.0885,
        0.156,
        0.21,
        0.2208,
        0.1915,
        0.0945
      ],
      "ev_score": 0.4545,
      "branches": [
        {
          "label": "Win the next fight",
          "prob": 0.366,
          "expected_placement": 4.8756830601092895
        },
        {
          "label": "Lose the next fight",
          "prob": 0.634,
          "expected_placement": 5.754337539432177
        }
      ],
      "explanation": "Greedy \u2014 banks gold and interest, but risks bleeding out while the board is weak (3% less top-4 than best)."
    },
    {
      "key": "roll_10",
      "label": "Roll to 10",
      "expected_placement": 5.44,
      "top4_rate": 0.265,
      "first_rate": 0.0022,
      "bot4_rate": 0.735,
      "risk": 1.498,
      "distribution": [
        0.0022,
        0.029,
        0.0757,
        0.158,
        0.228,
        0.2442,
        0.186,
        0.0767
      ],
      "ev_score": 0.4055,
      "branches": [
        {
          "label": "Win the next fight",
          "prob": 0.51325,
          "expected_placement": 5.1320019483682415
        },
        {
          "label": "Lose the next fight",
          "prob": 0.48675,
          "expected_placement": 5.766820749871598
        }
      ],
      "explanation": "Spends gold to find upgrades now; stabilizes the board at some economic cost (5% less top-4 than best)."
    },
    {
      "key": "roll_20",
      "label": "Roll to 20",
      "expected_placement": 5.43,
      "top4_rate": 0.2597,
      "first_rate": 0.0032,
      "bot4_rate": 0.7402,
      "risk": 1.492,
      "distribution": [
        0.0032,
        0.0307,
        0.0732,
        0.1525,
        0.2362,
        0.2442,
        0.189,
        0.0707
      ],
      "ev_score": 0.4042,
      "branches": [
        {
          "label": "Win the next fight",
          "prob": 0.502,
          "expected_placement": 5.116035856573705
        },
        {
          "label": "Lose the next fight",
          "prob": 0.498,
          "expected_placement": 5.746987951807229
        }
      ],
      "explanation": "Spends gold to find upgrades now; stabilizes the board at some economic cost (5% less top-4 than best)."
    },
    {
      "key": "roll_0",
      "label": "Roll to 0 (all-in)",
      "expected_placement": 5.73,
      "top4_rate": 0.2003,
      "first_rate": 0.0008,
      "bot4_rate": 0.7997,
      "risk": 1.407,
      "distribution": [
        0.0008,
        0.0147,
        0.0537,
        0.131,
        0.1983,
        0.2807,
        0.2298,
        0.091
      ],
      "ev_score": 0.2858,
      "branches": [
        {
          "label": "Win the next fight",
          "prob": 0.52775,
          "expected_placement": 5.481288488867835
        },
        {
          "label": "Lose the next fight",
          "prob": 0.47225,
          "expected_placement": 6.002646903123345
        }
      ],
      "explanation": "Maximum stabilization now \u2014 strongest immediate board, worst long-term economy (11% less top-4 than best)."
    },
    {
      "key": "level_7",
      "label": "Level to 7",
      "expected_placement": 5.83,
      "top4_rate": 0.179,
      "first_rate": 0.001,
      "bot4_rate": 0.821,
      "risk": 1.401,
      "distribution": [
        0.001,
        0.0123,
        0.0457,
        0.12,
        0.2008,
        0.2645,
        0.2487,
        0.107
      ],
      "ev_score": 0.2522,
      "branches": [
        {
          "label": "Win the next fight",
          "prob": 0.475,
          "expected_placement": 5.62578947368421
        },
        {
          "label": "Lose the next fight",
          "prob": 0.525,
          "expected_placement": 6.016190476190476
        }
      ],
      "explanation": "Raises your unit cap and shop odds; helps the ceiling but may not stabilize this turn (13% less top-4 than best)."
    }
  ],
  "best_key": "roll_30",
  "summary": "In this midgame spot with health to spare (58 HP, 42 gold, weak board) against a fast, strong lobby, the highest-EV line for securing a top-4 is \"Roll to 30\": 31% top-4, 0% first, average placement 5.3. Your board is behind the lobby, so converting gold into board strength now buys the time your economy needs to pay off.",
  "n_rollouts": 4000,
  "seed": 3675374413,
  "elapsed_ms": 7486.1,
  "cached": false
} as const;
